os:
  - linux
sudo: true
language: node_js
addons:
  apt:
    sources:
    - libgd2-xpm-dev
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "4.1"
  - "0.12"
  - "0.10"
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i
notifications:
  email:
    - vebruijn@gmail.com
