language: node_js

os:
  - linux

node_js:
  - "0.12"
  - "0.10"
  - "4.3"

sudo: required

env:
 - TRAVIS_OS_UNAME=$(uname -s)

install:
 - if [[ $TRAVIS_OS_UNAME = 'Linux' ]]; then bash travis-linux-deps.sh; fi
 - if [[ $TRAVIS_OS_UNAME = 'Darwin' ]]; then bash travis-osx-deps.sh; fi

notifications:
  email:
    - vebruijn@gmail.com
