language: node_js

os:
  - linux

node_js:
  - "4.1"
  - "0.12"
  - "0.10"

sudo: false

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i

notifications:
  email:
    - vebruijn@gmail.com

addons:
  apt:
    sources:
    - libgd2-xpm-dev
    packages:
    - g++-4.8
